'''
Constants file
'''
ROW_COUNT = 8
COLUMN_COUNT = 8
BOARD_LENGTH = 8

# This sets the WIDTH and HEIGHT of each grid location
WIDTH = 80
HEIGHT = 80

# This sets the margin between each cell
# and on the edges of the screen.
MARGIN = 5
CAPTURE_MARGIN = 2 # in columns

BOARD_OFFSET_X = (WIDTH + MARGIN) * CAPTURE_MARGIN
BOARD_OFFSET_Y = 0

LEFT_CAPTURE_X = MARGIN + WIDTH // 2
RIGHT_CAPTURE_X = BOARD_OFFSET_X + (WIDTH + MARGIN) * (COLUMN_COUNT + CAPTURE_MARGIN) - WIDTH // 2

BASE_Y = BOARD_OFFSET_Y + MARGIN + HEIGHT // 2

# Do the math to figure out our screen dimensions
WINDOW_WIDTH = (WIDTH + MARGIN) * (COLUMN_COUNT + CAPTURE_MARGIN * 2) + MARGIN
WINDOW_HEIGHT = (HEIGHT + MARGIN) * ROW_COUNT + MARGIN
WINDOW_TITLE = "Welcome to Chess!"

SPRITE_SCALE = 1

WINNER_BOX_WIDTH = WINDOW_WIDTH / 2
WINNER_BOX_HEIGHT = WINDOW_HEIGHT / 2 + 100
BUTTON_WIDTH = 300
GAME_OVER_FONT_SIZE = 30

COLOR_VIEW_TEXT_W = WINDOW_WIDTH / 2
COLOR_VIEW_TEXT_H = WINDOW_HEIGHT - 100

CAPTURED_PIECE_LIMIT = 12

PLAYER_TURN_BOX_W = WINDOW_WIDTH - 50
PLAYER_TURN_BOX_H = WINDOW_HEIGHT - 40
PLAYER_TURN_TEXT_W = WINDOW_WIDTH - 85
PLAYER_TURN_TEXT_H = WINDOW_HEIGHT - 60

COLOR_ALIGN_X = 20
COLOR_ALIGN_Y = -20

MENU_TEXT_W = WINDOW_WIDTH / 2
MENU_TEXT_H = WINDOW_HEIGHT / 2 + 200

MENU_FONT_SIZE = 30
PROMOTION_FONT_SIZE = 30

PROMOTION_TEXT_W = WINDOW_WIDTH / 2
PROMOTION_TEXT_H = WINDOW_HEIGHT - 100
